on:
  push:
    branches:
      - main
      - login-gcr.io # @note: use any development branch you would like

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # checkout code
      - uses: actions/checkout@v4

      # authenticate with GCP with workload identity provider
      - uses: 'google-github-actions/auth@v2'
        id: auth
        name: Authenticate to GCP
        with:
          project_id: 'cs-1660-435323' # update with your project ID
          workload_identity_provider: 'projects/875452116534/locations/global/workloadIdentityPools/github-actions-pool/providers/my-repo' # update with your Workload Identity Pool

      # configure/login with docker
      - name: gcloud Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # setup docker buildx
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/cs-1660-435323/assignment3/node-demo:test

# @note: you can use regular docker commands instead of the shared action
#      - name: Build and Push Without Buildx
#        run: |
#          docker build -t us-central1.pkg.dev/cs-1660-435323/assignment3/[IMAGE NAME]:[TAG] .
#          docker push us-central1.pkg.dev/cs-1660-435323/assignment3/[IMAGE NAME]:[TAG]
#          --> us-central1.pkg.dev/cc-fall2024/dansc0de/node-demo:v1 <--